name: project_automation

on:
  issues:
    types: [opened, labeled, closed]
  pull_request:
    types: [opened]
  release:
    types: [created]

jobs:
  handle_event:
    runs-on: ubuntu-latest
    steps:
    - uses: takb/project-board@master
      with:
        token: "${{ secrets.PROJECT_AUTOMATION }}"
        owner: "takb"
        repo: "zuiso"
        project: "1"
        columnbylabel: '{":bug: bug": "Urgent"}'
        ignorecolumnnames: "In progress,Review in progress,Reviewer approved,Done"
