name: project_automation_labels

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.PROJECT_AUTOMATION }}"
        project-url: "https://github.com/takb/zuiso/projects/1"
        column-name: "Urgent"
        label-name: ":bug: bug"
        columns-to-ignore: "Urgent,Assigned,In progress,Review,Awaiting release,Last release"
