name: project_automation

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.PROJECT_AUTOMATION }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to backlog project
    steps:
    - name: handle_add # Assign NEW issues and NEW pull requests to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/takb/zuiso/projects/1'

#    - name: handle_add_labeled # Assign NEW issues and NEW pull requests to project 1
 #     uses: srggrs/assign-one-project-github-action@1.2.0
  #    if: "github.event.action == 'opened' && contains(github.event.issue.labels.*.name, ':bug: bug') || contains(github.event.pull_request.labels.*.name, ':bug: bug')"
   #   with:
    #    project: 'https://github.com/takb/zuiso/projects/1'
     #   column_name: 'Urgent'

    - name: handle_label # Assign issues with `:bug: bug` label to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: "contains(github.event.issue.labels.*.name, ':bug: bug') || contains(github.event.pull_request.labels.*.name, ':bug: bug')"
      with:
        project: 'https://github.com/takb/zuiso/projects/1'
        column_name: 'Urgent'
